"use strict";

const path = require("path");
const { spawnSync } = require("child_process");

const PROJECT_ROOT = path.resolve(__dirname, "..", "..");

const syntaxTargets = [
  "src/server.js",
  "src/app.js",
  "src/services/member.service.js",
  "src/controllers/admin.controller.js",
  "src/routes/admin.routes.js",
  "src/admin-ui/app.js",
  "src/admin-audit-ui/app.js",
  "src/admin-wheel-ui/app.js",
  "src/services/wheel.service.js",
  "src/controllers/wheel.controller.js",
  "src/routes/wheel.routes.js",
  "src/middleware/wheelMemberAuth.js",
  "prisma/seed.js",
  "src/staging-scripts/stagingSafety.js",
  "src/staging-scripts/stagingDbCheck.js",
  "src/staging-scripts/stagingDbSeed.js",
  "src/staging-scripts/stagingDemoSeed.js",
  "src/staging-scripts/stagingReleaseGateSmoke.js",
  "src/staging-scripts/stagingUatSmoke.js",
  "src/integration-tests/payment.mock-test.js",
  "src/integration-tests/bank.mock-test.js",
  "src/integration-tests/sms.mock-test.js",
  "src/integration-tests/slip-ocr.mock-test.js",
  "src/integration-tests/game.mock-test.js",
  "src/local-smoke-tests/stagingPreflight.js",
  "src/local-smoke-tests/stagingSmoke.js",
  "src/local-smoke-tests/stagingReleaseReadinessSmoke.js",
  "src/local-smoke-tests/stagingDeployReadinessPackSmoke.js",
  "src/local-smoke-tests/disposableStagingDbDryRunPackSmoke.js",
  "src/staging-scripts/disposableStagingDbReadOnlyProbe.js",
  "src/local-smoke-tests/disposableStagingDbReadOnlyProbeSmoke.js",
  "src/local-smoke-tests/disposableStagingDbReadOnlyProbeRuntimeHarnessSmoke.js",
  "src/local-smoke-tests/disposableStagingDbReadOnlyProbeRuntimeHarness.js",
  "src/local-smoke-tests/productionReadinessAuditSmoke.js",
  "src/local-smoke-tests/productionSafetyDryRunSmoke.js",
  "src/local-smoke-tests/monitoringBackupRunbookSmoke.js",
  "src/local-smoke-tests/financialLedgerHardeningSmoke.js",
  "src/local-smoke-tests/financialLedgerRuntimeContractSmoke.js",
  "src/local-smoke-tests/financialLedgerSchemaDryRunSmoke.js",
  "src/ledger-mock/financialLedgerMockHarness.js",
  "src/local-smoke-tests/financialLedgerMockRuntimeHarnessSmoke.js",
  "src/ledger-mock/financialLedgerReconciliationMockReports.js",
  "src/admin-reconciliation-readonly-ui/app.js",
  "src/local-smoke-tests/financialLedgerReconciliationMockReportsSmoke.js",
  "src/local-smoke-tests/financialLedgerLiveIntegrationCertificationSmoke.js",
  "src/local-smoke-tests/financialLedgerStagingDryRunMigrationSmoke.js",
  "src/local-smoke-tests/adminWorkScheduleUiSmoke.js",
  "src/local-smoke-tests/adminAuditSecuritySmoke.js",
  "src/local-smoke-tests/adminRoleManagementSmoke.js",
  "src/local-smoke-tests/adminWheelUiSmoke.js",
  "src/local-smoke-tests/adminWheelRuntimeSmoke.js",
  "src/local-smoke-tests/adminBrowserRoutesSmoke.js",
  "src/local-smoke-tests/adminMemberHistoryReadOnlySmoke.js",
  "src/local-smoke-tests/adminBackofficeReadOnlyIntegrationSmoke.js",
  "src/local-smoke-tests/adminGuardedBankAccountReviewSmoke.js",
  "src/local-smoke-tests/adminOperatorHandoffSmoke.js",
  "src/local-smoke-tests/adminBankAccountReviewReleasePackSmoke.js",
  "src/payment-provider-mock/paymentProviderContract.js",
  "src/payment-provider-mock/paymentProviderMockHarness.js",
  "src/local-smoke-tests/paymentProviderContractSmoke.js",
  "src/game-provider-mock/oroplaySeamlessContract.js",
  "src/game-provider-mock/oroplaySeamlessMockHarness.js",
  "src/local-smoke-tests/oroplaySeamlessContractSmoke.js",
  "src/game-provider-mock/oroplayCallbackBoundary.js",
  "src/local-smoke-tests/oroplayCallbackBoundarySmoke.js",
  "src/game-provider-mock/oroplayCallbackStubContract.js",
  "src/controllers/oroplayCallbackStub.controller.js",
  "src/routes/oroplayCallbackStub.routes.js",
  "src/local-smoke-tests/oroplayCallbackStubSmoke.js",
  "src/game-provider-mock/oroplayCallbackReadinessContract.js",
  "src/game-provider-mock/oroplayCallbackReadinessHarness.js",
  "src/local-smoke-tests/oroplayCallbackReadinessSmoke.js",
  "src/game-provider-mock/oroplayCallbackRuntimeSimulator.js",
  "src/game-provider-mock/oroplayCallbackRuntimeScenarios.js",
  "src/local-smoke-tests/oroplayCallbackRuntimeSimulationSmoke.js",
  "src/game-provider-mock/oroplayCallbackRuntimeAdapterContract.js",
  "src/game-provider-mock/oroplayWalletLedgerBridgeDesign.js",
  "src/local-smoke-tests/oroplayCallbackRuntimeAdapterContractSmoke.js",
  "src/game-provider-mock/oroplayCallbackRuntimeExecutionPlan.js",
  "src/game-provider-mock/oroplayCallbackRuntimeGate.js",
  "src/local-smoke-tests/oroplayCallbackRuntimeExecutionPlanSmoke.js",
  "src/game-provider-mock/oroplayCallbackRuntimeReadinessGate.js",
  "src/game-provider-mock/oroplayCallbackPreImplementationCertificationPack.js",
  "src/local-smoke-tests/oroplayCallbackRuntimeReadinessGateSmoke.js",
  "src/game-provider-mock/oroplayCallbackImplementationDesignFreeze.js",
  "src/game-provider-mock/oroplayCallbackStagingActivationPlan.js",
  "src/local-smoke-tests/oroplayCallbackImplementationDesignFreezeSmoke.js",
  "src/game-provider-mock/oroplayCallbackStagingWiringPrecheck.js",
  "src/local-smoke-tests/oroplayCallbackStagingWiringPrecheckSmoke.js",
  "src/game-provider-mock/oroplayCallbackRuntimeShadowInvoker.js",
  "src/game-provider-mock/oroplayCallbackRuntimeShadowFixtures.js",
  "src/local-smoke-tests/oroplayCallbackRuntimeShadowInvocationSmoke.js",
  "src/game-provider-mock/oroplayCallbackRequestResponseEnvelope.js",
  "src/game-provider-mock/oroplayCallbackRequestResponseFixtures.js",
  "src/local-smoke-tests/oroplayCallbackRequestResponseEnvelopeSmoke.js",
  "src/game-provider-mock/oroplayCallbackControllerFacadeDryRun.js",
  "src/game-provider-mock/oroplayCallbackControllerFacadeFixtures.js",
  "src/local-smoke-tests/oroplayCallbackControllerFacadeDryRunSmoke.js",
  "src/game-provider-mock/oroplayCallbackStagingRouteWiringDesign.js",
  "src/game-provider-mock/oroplayCallbackStagingRouteWiringFixtures.js",
  "src/local-smoke-tests/oroplayCallbackStagingRouteWiringDesignSmoke.js",
  "src/payment-provider-mock/memberQrDepositUxContract.js",
  "src/payment-provider-mock/memberQrDepositMockHarness.js",
  "src/local-smoke-tests/memberQrDepositUxSmoke.js",
  "src/game-provider-mock/oro5tPublicAliasPostImplementationValidationBoundary.js",
  "src/game-provider-mock/oro5tPublicAliasPostImplementationValidationBoundaryFixtures.js",
  "src/local-smoke-tests/oro5tPublicAliasPostImplementationValidationBoundarySmoke.js",
  "src/local-smoke-tests/oro5tSmoke.js",
  "src/game-provider-mock/oro5uRuntimeTrafficAuthorizationRequestReadinessBoundary.js",
  "src/game-provider-mock/oro5uRuntimeTrafficAuthorizationRequestReadinessBoundaryFixtures.js",
  "src/local-smoke-tests/oro5uRuntimeTrafficAuthorizationRequestReadinessBoundarySmoke.js",
  "src/local-smoke-tests/oro5uSmoke.js",
  "src/game-provider-mock/oro5vRuntimeTrafficAuthorizationRequestSubmissionBoundary.js",
  "src/game-provider-mock/oro5vRuntimeTrafficAuthorizationRequestSubmissionBoundaryFixtures.js",
  "src/local-smoke-tests/oro5vRuntimeTrafficAuthorizationRequestSubmissionBoundarySmoke.js",
  "src/local-smoke-tests/oro5vSmoke.js",
  "src/game-provider-mock/oro5wRuntimeTrafficAuthorizationDecisionBoundary.js",
  "src/game-provider-mock/oro5wRuntimeTrafficAuthorizationDecisionBoundaryFixtures.js",
  "src/local-smoke-tests/oro5wRuntimeTrafficAuthorizationDecisionBoundarySmoke.js",
  "src/local-smoke-tests/oro5wSmoke.js",
  "src/game-provider-mock/oro5xRuntimeTrafficEnablementBoundary.js",
  "src/game-provider-mock/oro5xRuntimeTrafficEnablementBoundaryFixtures.js",
  "src/local-smoke-tests/oro5xRuntimeTrafficEnablementBoundarySmoke.js",
  "src/local-smoke-tests/oro5xSmoke.js",
  "src/game-provider-mock/oro5yRuntimeTrafficPostEnablementValidationBoundary.js",
  "src/game-provider-mock/oro5yRuntimeTrafficPostEnablementValidationBoundaryFixtures.js",
  "src/local-smoke-tests/oro5yRuntimeTrafficPostEnablementValidationBoundarySmoke.js",
  "src/local-smoke-tests/oro5ySmoke.js",
  "src/game-provider-mock/oro5zLiveTrafficAuthorizationRequestBoundary.js",
  "src/game-provider-mock/oro5zLiveTrafficAuthorizationRequestBoundaryFixtures.js",
  "src/local-smoke-tests/oro5zLiveTrafficAuthorizationRequestBoundarySmoke.js",
  "src/local-smoke-tests/oro5zSmoke.js",
  "src/game-provider-mock/oro6aLiveTrafficAuthorizationDecisionBoundary.js",
  "src/game-provider-mock/oro6aLiveTrafficAuthorizationDecisionBoundaryFixtures.js",
  "src/local-smoke-tests/oro6aLiveTrafficAuthorizationDecisionBoundarySmoke.js",
  "src/local-smoke-tests/oro6aSmoke.js",
  "src/game-provider-mock/oro6bLiveTrafficEnablementReadinessBoundary.js",
  "src/game-provider-mock/oro6bLiveTrafficEnablementReadinessBoundaryFixtures.js",
  "src/local-smoke-tests/oro6bLiveTrafficEnablementReadinessBoundarySmoke.js",
  "src/local-smoke-tests/oro6bSmoke.js",
  "src/game-provider-mock/oro6cLiveTrafficEnablementBoundary.js",
  "src/game-provider-mock/oro6cLiveTrafficEnablementBoundaryFixtures.js",
  "src/local-smoke-tests/oro6cLiveTrafficEnablementBoundarySmoke.js",
  "src/local-smoke-tests/oro6cSmoke.js",
  "src/game-provider-mock/oro6dLiveTrafficPostEnablementValidationBoundary.js",
  "src/game-provider-mock/oro6dLiveTrafficPostEnablementValidationBoundaryFixtures.js",
  "src/local-smoke-tests/oro6dLiveTrafficPostEnablementValidationBoundarySmoke.js",
  "src/local-smoke-tests/oro6dSmoke.js",
  "src/game-provider-mock/oro6eLiveTrafficExternalCallAuthorizationRequestBoundary.js",
  "src/game-provider-mock/oro6eLiveTrafficExternalCallAuthorizationRequestBoundaryFixtures.js",
  "src/local-smoke-tests/oro6eLiveTrafficExternalCallAuthorizationRequestBoundarySmoke.js",
  "src/local-smoke-tests/oro6eSmoke.js",
  "src/local-smoke-tests/masterSpecMappingSmoke.js",
  "src/local-smoke-tests/wheelSmoke.js",
  "src/local-smoke-tests/runProjectCheck.js",
  "src/local-smoke-tests/runSafetyCheck.js",
];

function runNode(label, args) {
  console.log(`[check] ${label}`);
  const result = spawnSync(process.execPath, args, {
    cwd: PROJECT_ROOT,
    env: process.env,
    stdio: "inherit",
    shell: false,
  });

  if (result.error) {
    console.error(`[check] failed to start: ${result.error.message}`);
    process.exit(1);
  }

  if (result.signal) {
    console.error(`[check] stopped by signal: ${result.signal}`);
    process.exit(1);
  }

  if (result.status !== 0) {
    process.exit(typeof result.status === "number" ? result.status : 1);
  }
}

for (const target of syntaxTargets) {
  runNode(`node --check ${target}`, ["--check", target]);
}

runNode("node src/local-smoke-tests/runSafetyCheck.js", ["src/local-smoke-tests/runSafetyCheck.js"]);

console.log("[check] PASS");
